# Generated by Django 3.2.16 on 2022-11-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default='описание', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='polls/media/questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='short_description',
            field=models.CharField(default='описание', max_length=400),
            preserve_default=False,
        ),
    ]
