# Generated by Django 3.2.16 on 2022-11-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20221103_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='percent_votes',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
    ]
